language: go

go:
  - 1.8

script:
  - go build -x -v ./...
  - go test -x -v ./...

notifications:
  email:
    recipients:
      - manparveshsinghrandhawa@gmail.com
    on_success: change
    on_failure: always